[package]
name = "vscode-custom-build-launcher"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
winres = "0.1.12"

[dependencies]
getargs = "0.5.0"
smallvec = "1.10.0"
